
const MOVABELS = {
    character: {
        IMAGES_IDLE: [
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_000.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_001.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_002.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_003.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_004.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_005.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_006.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_007.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_008.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_009.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_010.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_011.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_012.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_013.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_014.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_015.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_016.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle/0_Dark_Elves_Idle_017.png',
        ],
        IMAGES_LONG_IDLE: [
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_000.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_001.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_002.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_003.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_004.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_005.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_006.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_007.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_008.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_009.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_010.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_011.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_012.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_013.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_014.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_015.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_016.png',
            'gameassets/Elves/PNG/PNG Sequences/Idle Blinking/0_Dark_Elves_Idle Blinking_017.png',
        ],
        IMAGES_WALK: [
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_000.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_001.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_002.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_003.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_004.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_005.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_006.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_007.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_008.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_009.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_010.png',
            'gameassets/Elves/PNG/PNG Sequences/Running/0_Dark_Elves_Running_011.png',
        ],
        IMAGES_JUMPING: [
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_000.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_001.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_002.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_003.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_004.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_005.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Loop/0_Dark_Elves_Jump Loop_000.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Loop/0_Dark_Elves_Jump Loop_001.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Loop/0_Dark_Elves_Jump Loop_002.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Loop/0_Dark_Elves_Jump Loop_003.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Loop/0_Dark_Elves_Jump Loop_004.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Loop/0_Dark_Elves_Jump Loop_005.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_005.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_004.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_003.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_001.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_002.png',
            'gameassets/Elves/PNG/PNG Sequences/Jump Start/0_Dark_Elves_Jump Start_000.png',
        ],
        IMAGES_HURT: [
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_000.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_001.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_002.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_003.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_004.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_005.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_006.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_007.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_008.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_009.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_010.png',
            'gameassets/Elves/PNG/PNG Sequences/Hurt/0_Dark_Elves_Hurt_011.png',
        ],
        IMAGES_DYING: [
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_000.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_001.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_002.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_003.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_004.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_005.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_006.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_007.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_008.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_009.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_010.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_011.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_012.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_013.png',
            'gameassets/Elves/PNG/PNG Sequences/Dying/0_Dark_Elves_Dying_014.png',  
        ],
        IMAGES_ATTACK: [
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_1.png',
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_2.png',
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_3.png',
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_4.png',
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_5.png',
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_6.png',
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_7.png',
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_8.png',
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_9.png',
                'gameassets/Elves/PNG/PNG Sequences/attack/Explosion_10.png',

    ]
    },
    
    archer:{
        IMAGES_IDLE: [
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_000.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_001.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_002.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_003.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_004.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_005.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_006.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_007.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_008.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_009.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_010.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_011.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_012.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_013.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_014.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_015.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_016.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Idle/0_Archer_Idle_017.png',
        ],
        IMAGES_WALK: [
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_000.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_001.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_002.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_003.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_004.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_005.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_006.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_007.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_008.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_009.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_010.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Running/0_Archer_Running_011.png',
        ],
        IMAGES_DYING: [
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_000.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_001.png',  
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_002.png', 
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_003.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_004.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_005.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_006.png', 
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_007.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_008.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_009.png', 
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_010.png', 
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_011.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_012.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_013.png',
            'gameassets/Archer_2/PNG/PNG Sequences/Dying/0_Archer_Dying_014.png', 
        ],
    },

    boss: {
        IMAGES_IDLE: [
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_000.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_001.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_002.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_003.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_004.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_005.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_006.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_007.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_008.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_009.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_010.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_011.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_012.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_013.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_014.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_015.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_016.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Idle/0_Hell_Knight_Idle_017.png',
        ],
        IMAGES_DYING: [
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_000.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_001.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_002.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_003.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_004.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_005.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_006.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_007.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_008.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_009.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_010.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_011.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_012.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_013.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Dying/0_Hell_Knight_Dying_014.png',
        ],
        IMAGES_WALK: [
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_000.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_001.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_002.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_003.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_004.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_005.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_006.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_007.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_008.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_009.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_010.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_011.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_012.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_013.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_014.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_015.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_016.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_017.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_018.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_019.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_020.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_021.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_022.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Walking/0_Hell_Knight_Walking_023.png',

        ],
        IMAGES_ATTACK: [
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_000.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_001.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_002.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_003.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_004.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_005.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_006.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_007.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_008.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_009.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_010.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Slashing/0_Hell_Knight_Slashing_011.png',
        ],
        IMAGES_JUMP: [
            'gameassets/Hell_Knight/PNG/PNG Sequences/Falling Down/0_Hell_Knight_Falling Down_000.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Falling Down/0_Hell_Knight_Falling Down_001.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Falling Down/0_Hell_Knight_Falling Down_002.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Falling Down/0_Hell_Knight_Falling Down_003.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Falling Down/0_Hell_Knight_Falling Down_004.png',
            'gameassets/Hell_Knight/PNG/PNG Sequences/Falling Down/0_Hell_Knight_Falling Down_005.png',
        ],
    }
};

const preloadStartImg = [
    'gameassets/img/game-background-image.png',
    'gameassets/img/icons/soundmute.png',
    'gameassets/img/icons/soundOn.png',
    'gameassets/img/lose.png',
    'gameassets/img/win.png',
    'gameassets/Collectable Object/Life.png',
    'gameassets/Collectable Object/mana.png',
  '  gameassets/Collectable Object/Coin_01.png'

];